WPM = 15
FREQ = 144.42
BEACON = "TEST DE ON3URE         VANDAAG IS HET BEACON LES          LES 1 PIO IS GEEN GOED IDEE VOOR EEN BEACON WEGENS HARMONISCHEN ALL OVER THE PLACE             MET ZO EEN SI CHIPEKE KOMT DAT ALLEMAAL VREE GOE             73"
BEACONDELAY = 30 # IN WORDS