WPM = 15
FREQ = 144420
BEACON = "TEST DE ON3URE         VANDAAG IS HET VHF BEACON LES          IN DE PLAATS VAN EEN CRYSTAL GEBRUIKEN WE DE OUTPUT VAN DE GPS        DE GPS KAN JE WIJSMAKEN DAT HIJ 24MHZ MOET LEVEREN ONGEACHT ER LOCK IS ZO BLIJFT ONS BAKEN MOOI OP FREQUENTIE !             73"
BEACONDELAY = 30 # IN WORDS